name: Build and deploy

on:
  push:
    branches:
      - ci/cd
jobs:
  build-deploy:
    name: build and deploy tutorial
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: checkout code
        uses: actions/setup-java@v3
        with:
          distribution : 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml
